### ISSUE TITLE
contrail provisionning failing

### ISSUE THREAD

**Issue by DEEM78** [zioc/contrail-devstack-plugin#54]
Dear all

I am facing a problem witht e contrail provisionning step during the stack.sh process. Eventhough this step is considered as optionnel as the process continue and finished with success, I never got ssh access to the VM that I created.

when I check the status of the vrouter via ip netns the output was empty where it is supposed to return the reference of the vrouter namespace

I am using the PIKE version of devstack 

Below the error that I got during the stack.sh process

2018-05-23 14:02:24.936 | ++ contrail/devstack/plugin.sh:source:389 :   echo_summary 'Provisionning contrail'
2018-05-23 14:02:24.937 | ++ devstack/stack.sh:echo_summary:426       :   [[ -t 3 ]]
2018-05-23 14:02:24.939 | ++ devstack/stack.sh:echo_summary:432       :   echo -e Provisionning contrail
2018-05-23 14:02:24.940 | ++ contrail/devstack/plugin.sh:source:392 :   local 'provision_api_args=--api_server_ip 10.194.67.34 --api_server_port 8082  --admin_user admin --admin_password admin --admin_tenant_name admin'
2018-05-23 14:02:24.942 | ++ contrail/devstack/plugin.sh:source:394 :   is_service_enabled contrail-vrouter
2018-05-23 14:02:24.952 | ++ functions-common:is_service_enabled:2184 :   return 0
2018-05-23 14:02:24.954 | ++ contrail/devstack/plugin.sh:source:395 :   /usr/share/contrail/provision_vrouter.py --api_server_ip 10.194.67.34 --api_server_port 8082 --admin_user admin --admin_password admin --admin_tenant_name admin --oper add --host_name test --host_ip 10.194.67.34
2018-05-23 14:02:25.148 | Traceback (most recent call last):
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/provision_vrouter.py", line 293, in <module>
2018-05-23 14:02:25.148 |     main()
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/provision_vrouter.py", line 289, in main
2018-05-23 14:02:25.148 |     VrouterProvisioner(args_str)
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/provision_vrouter.py", line 35, in __init__
2018-05-23 14:02:25.148 |     api_server_use_ssl=self._args.api_server_use_ssl)
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/vnc_admin_api.py", line 35, in __init__
2018-05-23 14:02:25.148 |     auth_host=self.auth_host)
2018-05-23 14:02:25.148 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 491, in __init__
2018-05-23 14:02:25.148 |     retry_on_error=False)
2018-05-23 14:02:25.148 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 1006, in _request
2018-05-23 14:02:25.148 |     raise ConnectionError
2018-05-23 14:02:25.148 | requests.exceptions.ConnectionError
2018-05-23 14:02:25.166 | ++ contrail/devstack/plugin.sh:source:397 :   /bin/true
2018-05-23 14:02:25.169 | ++ contrail/devstack/plugin.sh:source:399 :   is_service_enabled contrail-control
2018-05-23 14:02:25.187 | ++ functions-common:is_service_enabled:2184 :   return 0
2018-05-23 14:02:25.190 | ++ contrail/devstack/plugin.sh:source:400 :   /usr/share/contrail/provision_control.py --api_server_ip 10.194.67.34 --api_server_port 8082 --admin_user admin --admin_password admin --admin_tenant_name admin --oper add --host_name test --host_ip 10.194.67.34 --router_asn 64512
2018-05-23 14:02:25.429 | Traceback (most recent call last):
2018-05-23 14:02:25.429 |   File "/usr/share/contrail/provision_control.py", line 257, in <module>
2018-05-23 14:02:25.429 |     main()
2018-05-23 14:02:25.429 |   File "/usr/share/contrail/provision_control.py", line 253, in main
2018-05-23 14:02:25.430 |     ControlProvisioner(args_str)
2018-05-23 14:02:25.430 |   File "/usr/share/contrail/provision_control.py", line 65, in __init__
2018-05-23 14:02:25.430 |     peer_list=peer_list)
2018-05-23 14:02:25.430 |   File "/usr/share/contrail/provision_bgp.py", line 38, in __init__
2018-05-23 14:02:25.430 |     api_server_use_ssl=self._api_server_use_ssl)
2018-05-23 14:02:25.430 |   File "/usr/share/contrail/vnc_admin_api.py", line 35, in __init__
2018-05-23 14:02:25.430 |     auth_host=self.auth_host)
2018-05-23 14:02:25.430 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 491, in __init__
2018-05-23 14:02:25.430 |     retry_on_error=False)
2018-05-23 14:02:25.430 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 1006, in _request
2018-05-23 14:02:25.430 |     raise ConnectionError
2018-05-23 14:02:25.430 | requests.exceptions.ConnectionError
2018-05-23 14:02:25.447 | ++ contrail/devstack/plugin.sh:source:402 :   /bin/true
2018-05-23 14:02:25.451 | ++ contrail/devstack/plugin.sh:source:404 :   is_service_enabled contrail-api
2018-05-23 14:02:25.469 | ++ functions-common:is_service_enabled:2184 :   return 0
2018-05-23 14:02:25.471 | ++ contrail/devstack/plugin.sh:source:405 :   /usr/share/contrail/provision_linklocal.py --api_server_ip 10.194.67.34 --api_server_port 8082 --admin_user admin --admin_password admin --admin_tenant_name admin --oper add --linklocal_service_name metadata --linklocal_service_ip 169.254.169.254 --linklocal_service_port 80 --ipfabric_service_ip 10.194.67.34 --ipfabric_service_port 8775
2018-05-23 14:02:25.660 | Traceback (most recent call last):
2018-05-23 14:02:25.660 |   File "/usr/share/contrail/provision_linklocal.py", line 186, in <module>
2018-05-23 14:02:25.660 |     main()
2018-05-23 14:02:25.660 |   File "/usr/share/contrail/provision_linklocal.py", line 182, in main
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/provision_vrouter.py", line 293, in <module>
2018-05-23 14:02:25.148 |     main()
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/provision_vrouter.py", line 289, in main
2018-05-23 14:02:25.148 |     VrouterProvisioner(args_str)
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/provision_vrouter.py", line 35, in __init__
2018-05-23 14:02:25.148 |     api_server_use_ssl=self._args.api_server_use_ssl)
2018-05-23 14:02:25.148 |   File "/usr/share/contrail/vnc_admin_api.py", line 35, in __init__
2018-05-23 14:02:25.148 |     auth_host=self.auth_host)
2018-05-23 14:02:25.148 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 491, in __init__
2018-05-23 14:02:25.148 |     retry_on_error=False)
2018-05-23 14:02:25.148 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 1006, in _request
2018-05-23 14:02:25.148 |     raise ConnectionError
2018-05-23 14:02:25.148 | requests.exceptions.ConnectionError
2018-05-23 14:02:25.166 | ++ contrail/devstack/plugin.sh:source:397 :   /bin/true
2018-05-23 14:02:25.169 | ++ contrail/devstack/plugin.sh:source:399 :   is_service_enabled contrail-control
2018-05-23 14:02:25.187 | ++ functions-common:is_service_enabled:2184 :   return 0
2018-05-23 14:02:25.190 | ++ contrail/devstack/plugin.sh:source:400 :   /usr/share/contrail/provision_control.py --api_server_ip 10.194.67.34 --api_server_port 8082 --admin_user admin --admin_password admin --admin_tenant_name admin --oper add --host_name test --host_ip 10.194.67.34 --router_asn 64512
2018-05-23 14:02:25.429 | Traceback (most recent call last):
2018-05-23 14:02:25.429 |   File "/usr/share/contrail/provision_control.py", line 257, in <module>
2018-05-23 14:02:25.429 |     main()
2018-05-23 14:02:25.429 |   File "/usr/share/contrail/provision_control.py", line 253, in main
2018-05-23 14:02:25.430 |     ControlProvisioner(args_str)
2018-05-23 14:02:25.430 |   File "/usr/share/contrail/provision_control.py", line 65, in __init__
2018-05-23 14:02:25.430 |     peer_list=peer_list)
2018-05-23 14:02:25.430 |   File "/usr/share/contrail/provision_bgp.py", line 38, in __init__
2018-05-23 14:02:25.430 |     api_server_use_ssl=self._api_server_use_ssl)
2018-05-23 14:02:25.430 |   File "/usr/share/contrail/vnc_admin_api.py", line 35, in __init__
2018-05-23 14:02:25.430 |     auth_host=self.auth_host)
2018-05-23 14:02:25.430 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 491, in __init__
2018-05-23 14:02:25.430 |     retry_on_error=False)
2018-05-23 14:02:25.430 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 1006, in _request
2018-05-23 14:02:25.430 |     raise ConnectionError
2018-05-23 14:02:25.430 | requests.exceptions.ConnectionError
2018-05-23 14:02:25.447 | ++ contrail/devstack/plugin.sh:source:402 :   /bin/true
2018-05-23 14:02:25.451 | ++ contrail/devstack/plugin.sh:source:404 :   is_service_enabled contrail-api
2018-05-23 14:02:25.469 | ++ functions-common:is_service_enabled:2184 :   return 0
2018-05-23 14:02:25.471 | ++ /home/navi/openstack/contrail/devstack/plugin.sh:source:405 :   /usr/share/contrail/provision_linklocal.py --api_server_ip 10.194.67.34 --api_server_port 8082 --admin_user admin --admin_password admin --admin_tenant_name admin --oper add --linklocal_service_name metadata --linklocal_service_ip 169.254.169.254 --linklocal_service_port 80 --ipfabric_service_ip 10.194.67.34 --ipfabric_service_port 8775
2018-05-23 14:02:25.660 | Traceback (most recent call last):
2018-05-23 14:02:25.660 |   File "/usr/share/contrail/provision_linklocal.py", line 186, in <module>
2018-05-23 14:02:25.660 |     main()
2018-05-23 14:02:25.660 |   File "/usr/share/contrail/provision_linklocal.py", line 182, in main
2018-05-23 14:02:25.660 |     MetadataProvisioner(args_str)
2018-05-23 14:02:25.660 |   File "/usr/share/contrail/provision_linklocal.py", line 29, in __init__
2018-05-23 14:02:25.660 |     api_server_use_ssl=self._args.api_server_use_ssl)
2018-05-23 14:02:25.660 |   File "/usr/share/contrail/vnc_admin_api.py", line 35, in __init__
2018-05-23 14:02:25.660 |     auth_host=self.auth_host)
2018-05-23 14:02:25.660 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 491, in __init__
2018-05-23 14:02:25.660 |     retry_on_error=False)
2018-05-23 14:02:25.660 |   File "/usr/lib/python2.7/dist-packages/vnc_api/vnc_api.py", line 1006, in _request
2018-05-23 14:02:25.660 |     raise ConnectionError
2018-05-23 14:02:25.660 | requests.exceptions.ConnectionError

My local.conf

[[local|localrc]]
ADMIN_PASSWORD=admin
DATABASE_PASSWORD=root
RABBIT_PASSWORD=openstack
SERVICE_PASSWORD=$ADMIN_PASSWORD
SERVICE_TOKEN=admin

HOST_IP=10.194.67.34
CONTROLLER=10.194.67.34
SERVICE_HOST=$CONTROLLER
MYSQL_HOST=$HOST_IP
RABBIT_HOST=$HOST_IP

FORCE=yes
RECLONE=False
VERBOSE=True

GIT_BASE=https://git.openstack.org
DEST=~/openstack

LOGFILE=$DEST/logs/stack.sh.log
LOGDIR=$DEST/logs
LOGDAYS=2

disable_service dstat
disable_service n-novnc
disable_service n-cauth
disable_service tempest
enable_service placement_api
enable_service placement
enable_service heat

KEYSTONE_SECURITY_COMPLIANCE_ENABLED=False

USE_SSL=True

enable_plugin contrail https://github.com/zioc/contrail-devstack-plugin.git

VHOST_INTERFACE_NAME=eno1
Q_L3_ENABLED=True
VGW_MASQUERADE=True

LIBVIRT_FIREWALL_DRIVER=nova.virt.firewall.NoopFirewallDriver

enable_plugin networking-bgpvpn https://git.openstack.org/openstack/networking-bgpvpn.git stable/pike
NETWORKING_BGPVPN_DRIVER="BGPVPN:OpenContrail:networking_bgpvpn.neutron.services.service_drivers.opencontrail.opencontrail.OpenContrailBGPVPNDriver:default"

Thank you for your help

Regards

**Comment by Doude** [comment]
Hi,

It seems devstack Contrail plugin fails to provision Contrail first resources/config because it cannot reach the Contrail API. Could you look if the contrail API service have some intersting logs that could explain why it's failing with command `journalctl -u devstack@contrail-api` ?

**Comment by DEEM78** [comment]
Hello

Thank you for your prompt reply

Meanwhile, I solved my issue by removing the following line from my local.conf LIBVIRT_FIREWALL_DRIVER=nova.virt.firewall.NoopFirewallDriver

I guess the packets were not going through because of the firewall.

Regards
